<a href="https://colab.research.google.com/github/subiya-farooq/DataCleaning/blob/main/cafe_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [ ]:
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])

In [ ]:

df['Quantity'] = df['Quantity'].str.replace(",", "", regex=False)
df['Quantity'] = pd.to_numeric(df['Quantity'], errors="coerce")

In [ ]:
df['Quantity'].unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [ ]:
df['Quantity'].skew()

np.float64(-0.008092790056933747)

In [ ]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [ ]:
df['Price Per Unit'] = df['Price Per Unit'].str.replace(",", "", regex=False)
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors="coerce")

In [ ]:
df['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [ ]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].mean())

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(2), object(6)
memory usage: 625.1+ KB

In [ ]:
df = df.drop( columns=['Total Spent'])
df

,Transaction ID,Item,Quantity,Price Per Unit,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.000000,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.000000,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.000000,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.000000,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,Juice,3.0,2.949984,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.000000,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.949984,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.000000,Cash,In-store,2023-11-07

In [ ]:
df['Total Spent'] = df['Quantity'] * df['Price Per Unit']
df

,Transaction ID,Item,Quantity,Price Per Unit,Payment Method,Location,Transaction Date,Total Spent
0,TXN_1961373,Coffee,2.0,2.000000,Credit Card,Takeaway,2023-09-08,4.000000
1,TXN_4977031,Cake,4.0,3.000000,Cash,In-store,2023-05-16,12.000000
2,TXN_4271903,Cookie,4.0,1.000000,Credit Card,In-store,2023-07-19,4.000000
3,TXN_7034554,Salad,2.0,5.000000,UNKNOWN,UNKNOWN,2023-04-27,10.000000
4,TXN_3160411,Coffee,2.0,2.000000,Digital Wallet,In-store,2023-06-11,4.000000
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.000000,NaN,UNKNOWN,2023-08-30,4.000000
9996,TXN_9659401,Juice,3.0,2.949984,Digital Wallet,NaN,2023-06-02,8.849952
9997,TXN_5255387,Coffee,4.0,2.000000,Digital Wallet,NaN,2023-03-02,8.000000
9998,TXN_7695629,Cookie,3.0,2.949984,Digital Wallet,NaN,2023-12-02,8.849952
9999,TXN_6170729,Sandwich,3.0,4.000000,Cash,In-store,2023-11-07,12.000000

In [ ]:
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [ ]:
df['Payment Method'] = df['Payment Method'].replace('UNKNOWN', df['Payment Method'].mode()[0])
df

,Transaction ID,Item,Quantity,Price Per Unit,Payment Method,Location,Transaction Date,Total Spent
0,TXN_1961373,Coffee,2.0,2.000000,Credit Card,Takeaway,2023-09-08,4.000000
1,TXN_4977031,Cake,4.0,3.000000,Cash,In-store,2023-05-16,12.000000
2,TXN_4271903,Cookie,4.0,1.000000,Credit Card,In-store,2023-07-19,4.000000
3,TXN_7034554,Salad,2.0,5.000000,Digital Wallet,UNKNOWN,2023-04-27,10.000000
4,TXN_3160411,Coffee,2.0,2.000000,Digital Wallet,In-store,2023-06-11,4.000000
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.000000,NaN,UNKNOWN,2023-08-30,4.000000
9996,TXN_9659401,Juice,3.0,2.949984,Digital Wallet,NaN,2023-06-02,8.849952
9997,TXN_5255387,Coffee,4.0,2.000000,Digital Wallet,NaN,2023-03-02,8.000000
9998,TXN_7695629,Cookie,3.0,2.949984,Digital Wallet,NaN,2023-12-02,8.849952
9999,TXN_6170729,Sandwich,3.0,4.000000,Cash,In-store,2023-11-07,12.000000

In [ ]:
df['Payment Method'] = df['Payment Method'].fillna(df['Payment Method'].mode()[0])
df['Location'] = df['Location'  ].fillna(df['Location'].mode()[0])
df

,Transaction ID,Item,Quantity,Price Per Unit,Payment Method,Location,Transaction Date,Total Spent
0,TXN_1961373,Coffee,2.0,2.000000,Credit Card,Takeaway,2023-09-08,4.000000
1,TXN_4977031,Cake,4.0,3.000000,Cash,In-store,2023-05-16,12.000000
2,TXN_4271903,Cookie,4.0,1.000000,Credit Card,In-store,2023-07-19,4.000000
3,TXN_7034554,Salad,2.0,5.000000,Digital Wallet,UNKNOWN,2023-04-27,10.000000
4,TXN_3160411,Coffee,2.0,2.000000,Digital Wallet,In-store,2023-06-11,4.000000
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.000000,Digital Wallet,UNKNOWN,2023-08-30,4.000000
9996,TXN_9659401,Juice,3.0,2.949984,Digital Wallet,Takeaway,2023-06-02,8.849952
9997,TXN_5255387,Coffee,4.0,2.000000,Digital Wallet,Takeaway,2023-03-02,8.000000
9998,TXN_7695629,Cookie,3.0,2.949984,Digital Wallet,Takeaway,2023-12-02,8.849952
9999,TXN_6170729,Sandwich,3.0,4.000000,Cash,In-store,2023-11-07,12.000000

In [ ]:
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'Digital Wallet', 'ERROR'], dtype=object)

In [ ]:

df = pd.get_dummies(df, columns=['Payment Method'], drop_first=True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Location,Transaction Date,Total Spent,Payment Method_Credit Card,Payment Method_Digital Wallet,Payment Method_ERROR
0,TXN_1961373,Coffee,2.0,2.000000,Takeaway,2023-09-08,4.000000,True,False,False
1,TXN_4977031,Cake,4.0,3.000000,In-store,2023-05-16,12.000000,False,False,False
2,TXN_4271903,Cookie,4.0,1.000000,In-store,2023-07-19,4.000000,True,False,False
3,TXN_7034554,Salad,2.0,5.000000,UNKNOWN,2023-04-27,10.000000,False,True,False
4,TXN_3160411,Coffee,2.0,2.000000,In-store,2023-06-11,4.000000,False,True,False
...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.000000,UNKNOWN,2023-08-30,4.000000,False,True,False
9996,TXN_9659401,Juice,3.0,2.949984,Takeaway,2023-06-02,8.849952,False,True,False
9997,TXN_5255387,Coffee,4.0,2.000000,Takeaway,2023-03-02,8.000000,False,True,False
9998,TXN_7695629,Cookie,3.0,2.949984,Takeaway,2023-12-02,8.849952,False,True,False
9999,TXN_6170729,Sandwich,3.0,4.000000,In-store,2023-11-07,12.000000,False,False,False